In [66]:
from itertools import product as pr
from sympy import Matrix, Symbol, latex, sqrt, sin, cos, simplify, Trace, Sum, expand, solve, lambdify
from sympy.simplify.fu import fu, TR3
from sympy.matrices import eye, zeros, ones, diag
from sympy.physics.quantum import TensorProduct as tp, Dagger as dg
from numpy import pi, around
## trace
def tr(m): 
    return Trace(m).simplify()

pi

In [79]:
b1, b2, b3, b4 = 0.5**0.5*Matrix([1,0,0,0,0,1]), 0.5**0.5*Matrix([1,0,0,-1]), 0.5**0.5*Matrix([0,1,1,0]), 0.5**0.5*Matrix([0,1,-1,0])
rho =  lambda b: tp(b,dg(b))
rho1, rho2, rho3, rho4 = tp(b1,dg(b1)), tp(b2,dg(b2)), tp(b3,dg(b3)), tp(b4,dg(b4))
rhos = 1/4*ones(4,4)
rhod = 1/4*diag(1,1,1,1)

In [170]:
# type and actions
T1, T2, A1, A2 = [0], [0,1], [0,1,2], [0,1]
# Measure basis
phi1 = [lambda th, ph: Matrix([cos(ph)*cos(th), sin(ph)*cos(th), sin(th)]), lambda th, ph: Matrix([cos(ph)*sin(th), sin(ph)*sin(th), -cos(th)]),  lambda th, ph: Matrix([-sin(ph), cos(ph), 0])]
phi1i = [lambda th, ph: Matrix([cos(ph)*cos(th), 1j*sin(ph)*cos(th), sin(th)]), lambda th, ph: Matrix([cos(ph)*sin(th), 1j*sin(ph)*sin(th), -cos(th)]),  lambda th, ph: Matrix([-sin(ph), 1j*cos(ph), 0])]

phi2 = [lambda th: Matrix([cos(th), sin(th)]), lambda th: Matrix([sin(th), -cos(th)])]
phi2i = [lambda th: Matrix([cos(th), 1j*sin(th)]), lambda th: Matrix([sin(th), -1j*cos(th)])]
th = lambda player, typ: Symbol('theta'+'_'+str(typ)+'^'+str(player), real = True) 
ph = lambda player, typ: Symbol('phi'+'_'+str(typ)+'^'+str(player), real = True)

# pvm
# M = [lambda player, typ: phi[a](th(player, typ))*phi[a](th(player, typ)).T for a in list([0,1])]
M1 = [lambda player, typ: phi1[0](th(player, typ), ph(player, typ))*phi1[0](th(player, typ), ph(player, typ)).T, lambda player, typ: phi1[1](th(player, typ), ph(player, typ))*phi1[1](th(player, typ), ph(player, typ)).T, lambda player, typ: phi1[2](th(player, typ), ph(player, typ))*phi1[2](th(player, typ), ph(player, typ)).T]
M2 = [lambda player, typ: phi2[0](th(player, typ))*phi2[0](th(player, typ)).T, lambda player, typ: phi2[1](th(player, typ))*phi2[1](th(player, typ)).T]

M1i = [lambda player, typ: phi1i[0](th(player, typ), ph(player, typ))*phi1i[0](th(player, typ), ph(player, typ)).T, lambda player, typ: phi1i[1](th(player, typ), ph(player, typ))*phi1i[1](th(player, typ), ph(player, typ)).T, lambda player, typ: phi1i[2](th(player, typ), ph(player, typ))*phi1i[2](th(player, typ), ph(player, typ)).T]

Mi = [lambda player, typ: phi2i[0](th(player, typ))*phi2i[0](th(player, typ)).H, lambda player, typ: phi2i[1](th(player, typ))*phi2i[1](th(player, typ)).H]
## pvm numerical

In [196]:
def nQ(Q, x,y,z,a):
    f = lambdify([th(1,0), th(2,0), th(2,1), ph(1,0)], Q)
    return around(f(x, y, z, a), decimals=3)

def nQ1(Q, x, a, y1, b1, y2, b2):
    f = lambdify([th(1,0), ph(1,0), th(2,0), ph(2,0), th(2,1), ph(2,1)], Q)
    return around(f(x, a, y1, b1, y2, b2), decimals=3)



In [167]:
Q = Matrix([[simplify(tr(rho1*tp(M1[a1](1,t1), Mi[a2](2,t2)))) for (t1,t2) in list(pr(T1,T2))] for (a1,a2) in list(pr(A1,A2))])
Q

Matrix([
[0.5*sin(theta_0^1)**2*sin(theta_0^2)**2 + 0.5*cos(phi_0^1)**2*cos(theta_0^1)**2*cos(theta_0^2)**2, 0.5*sin(theta_0^1)**2*sin(theta_1^2)**2 + 0.5*cos(phi_0^1)**2*cos(theta_0^1)**2*cos(theta_1^2)**2],
[0.5*sin(theta_0^1)**2*cos(theta_0^2)**2 + 0.5*sin(theta_0^2)**2*cos(phi_0^1)**2*cos(theta_0^1)**2, 0.5*sin(theta_0^1)**2*cos(theta_1^2)**2 + 0.5*sin(theta_1^2)**2*cos(phi_0^1)**2*cos(theta_0^1)**2],
[0.5*sin(theta_0^1)**2*cos(phi_0^1)**2*cos(theta_0^2)**2 + 0.5*sin(theta_0^2)**2*cos(theta_0^1)**2, 0.5*sin(theta_0^1)**2*cos(phi_0^1)**2*cos(theta_1^2)**2 + 0.5*sin(theta_1^2)**2*cos(theta_0^1)**2],
[0.5*sin(theta_0^1)**2*sin(theta_0^2)**2*cos(phi_0^1)**2 + 0.5*cos(theta_0^1)**2*cos(theta_0^2)**2, 0.5*sin(theta_0^1)**2*sin(theta_1^2)**2*cos(phi_0^1)**2 + 0.5*cos(theta_0^1)**2*cos(theta_1^2)**2],
[                                                            0.5*sin(phi_0^1)**2*cos(theta_0^2)**2,                                                             0.5*sin(phi_0^1)**2*cos(theta_1

In [169]:
nQ(Q, pi/2, pi/2, 0, pi/2)

array([[0.5, 0. ],
       [0. , 0.5],
       [0. , 0. ],
       [0. , 0. ],
       [0. , 0.5],
       [0.5, 0. ]])

In [172]:
Q = Matrix([[simplify(tr(rho((1/2)**0.5*Matrix([1,0,0,0,0,0,0,0,1]))*tp(M1[a1](1,t1), M1i[a2](2,t2)))) for (t1,t2) in list(pr(T1,T2))] for (a1,a2) in list(pr(A1,A1))])
Q

Matrix([
[0.5*(sin(theta_0^1)*sin(theta_0^2) + cos(phi_0^1)*cos(phi_0^2)*cos(theta_0^1)*cos(theta_0^2))**2, 0.5*(sin(theta_0^1)*sin(theta_1^2) + cos(phi_0^1)*cos(phi_1^2)*cos(theta_0^1)*cos(theta_1^2))**2],
[0.5*(sin(theta_0^1)*cos(theta_0^2) - sin(theta_0^2)*cos(phi_0^1)*cos(phi_0^2)*cos(theta_0^1))**2, 0.5*(sin(theta_0^1)*cos(theta_1^2) - sin(theta_1^2)*cos(phi_0^1)*cos(phi_1^2)*cos(theta_0^1))**2],
[                                           0.5*sin(phi_0^2)**2*cos(phi_0^1)**2*cos(theta_0^1)**2,                                            0.5*sin(phi_1^2)**2*cos(phi_0^1)**2*cos(theta_0^1)**2],
[0.5*(sin(theta_0^1)*cos(phi_0^1)*cos(phi_0^2)*cos(theta_0^2) - sin(theta_0^2)*cos(theta_0^1))**2, 0.5*(sin(theta_0^1)*cos(phi_0^1)*cos(phi_1^2)*cos(theta_1^2) - sin(theta_1^2)*cos(theta_0^1))**2],
[0.5*(sin(theta_0^1)*sin(theta_0^2)*cos(phi_0^1)*cos(phi_0^2) + cos(theta_0^1)*cos(theta_0^2))**2, 0.5*(sin(theta_0^1)*sin(theta_1^2)*cos(phi_0^1)*cos(phi_1^2) + cos(theta_0^1)*cos(theta_1^2))**2],
[

In [180]:
nQ1(Q, pi/2, pi/2, pi/2, pi/2, pi/8, pi/8)

array([[0.5  , 0.073],
       [0.   , 0.427],
       [0.   , 0.   ],
       [0.   , 0.   ],
       [0.   , 0.   ],
       [0.   , 0.   ],
       [0.   , 0.364],
       [0.   , 0.062],
       [0.5  , 0.073]])

In [185]:
Q0 = Matrix([[simplify(tr(rho((1/3)**0.5*Matrix([1,0,0,0,-1j,0,0,0,1]))*tp(M1[a1](1,t1), M1i[a2](2,t2)))) for (t1,t2) in list(pr(T1,T2))] for (a1,a2) in list(pr(A1,A1))])
Q0

Matrix([
[0.333333333333333*(sin(theta_0^1)*sin(theta_0^2) + cos(theta_0^1)*cos(theta_0^2)*cos(phi_0^1 - phi_0^2))*(sin(theta_0^1)*sin(theta_0^2) + cos(theta_0^1)*cos(theta_0^2)*cos(phi_0^1 + phi_0^2)), 0.333333333333333*(sin(theta_0^1)*sin(theta_1^2) + cos(theta_0^1)*cos(theta_1^2)*cos(phi_0^1 - phi_1^2))*(sin(theta_0^1)*sin(theta_1^2) + cos(theta_0^1)*cos(theta_1^2)*cos(phi_0^1 + phi_1^2))],
[0.333333333333333*(sin(theta_0^1)*cos(theta_0^2) - sin(theta_0^2)*cos(theta_0^1)*cos(phi_0^1 - phi_0^2))*(sin(theta_0^1)*cos(theta_0^2) - sin(theta_0^2)*cos(theta_0^1)*cos(phi_0^1 + phi_0^2)), 0.333333333333333*(sin(theta_0^1)*cos(theta_1^2) - sin(theta_1^2)*cos(theta_0^1)*cos(phi_0^1 - phi_1^2))*(sin(theta_0^1)*cos(theta_1^2) - sin(theta_1^2)*cos(theta_0^1)*cos(phi_0^1 + phi_1^2))],
[                                                                                                             -0.333333333333333*sin(phi_0^1 - phi_0^2)*sin(phi_0^1 + phi_0^2)*cos(theta_0^1)**2,                      

In [189]:
nQ1(Q0, pi/2, pi/2, pi/2, pi/2, 0, 0)

array([[ 0.333,  0.   ],
       [ 0.   ,  0.333],
       [ 0.   , -0.   ],
       [-0.   ,  0.   ],
       [-0.333,  0.   ],
       [ 0.   , -0.333],
       [-0.   ,  0.333],
       [-0.   ,  0.   ],
       [ 0.333, -0.   ]])

In [192]:
Q1 = Matrix([[simplify(tr(rho((1/3)**0.5*Matrix([1,0,0,0,1,0,0,0,1]))*tp(M1[a1](1,t1), M1i[a2](2,t2)))) for (t1,t2) in list(pr(T1,T2))] for (a1,a2) in list(pr(A1,A1))])
Q1

Matrix([
[0.666666666666667*I*sin(phi_0^1)*sin(phi_0^2)*sin(theta_0^1)*sin(theta_0^2)*cos(theta_0^1)*cos(theta_0^2) + 0.666666666666667*I*sin(phi_0^1)*sin(phi_0^2)*cos(phi_0^1)*cos(phi_0^2)*cos(theta_0^1)**2*cos(theta_0^2)**2 + 0.666666666666667*sin(theta_0^1)*sin(theta_0^2)*cos(phi_0^1)*cos(phi_0^2)*cos(theta_0^1)*cos(theta_0^2) + 0.333333333333333*cos(phi_0^1)**2*cos(theta_0^1)**2*cos(theta_0^2)**2 + 0.333333333333333*cos(phi_0^2)**2*cos(theta_0^1)**2*cos(theta_0^2)**2 - 0.333333333333333*cos(theta_0^1)**2 - 0.333333333333333*cos(theta_0^2)**2 + 0.333333333333333, 0.666666666666667*I*sin(phi_0^1)*sin(phi_1^2)*sin(theta_0^1)*sin(theta_1^2)*cos(theta_0^1)*cos(theta_1^2) + 0.666666666666667*I*sin(phi_0^1)*sin(phi_1^2)*cos(phi_0^1)*cos(phi_1^2)*cos(theta_0^1)**2*cos(theta_1^2)**2 + 0.666666666666667*sin(theta_0^1)*sin(theta_1^2)*cos(phi_0^1)*cos(phi_1^2)*cos(theta_0^1)*cos(theta_1^2) + 0.333333333333333*cos(phi_0^1)**2*cos(theta_0^1)**2*cos(theta_1^2)**2 + 0.333333333333333*cos(phi_1^2)*

In [256]:
Qt10 = Matrix([[simplify(tr(rho((1/3)**0.5*Matrix([1,0,0,0,1,0,0,0,1]))*tp(M1[a1](1,t1), M1[a2](2,t2)))) for (t1,t2) in list(pr(T1,T2))] for (a1,a2) in list(pr(A1,A1))])
Qt10

Matrix([
[0.333333333333333*(sin(theta_0^1)*sin(theta_0^2) + cos(theta_0^1)*cos(theta_0^2)*cos(phi_0^1 - phi_0^2))**2, 0.333333333333333*(sin(theta_0^1)*sin(theta_1^2) + cos(theta_0^1)*cos(theta_1^2)*cos(phi_0^1 - phi_1^2))**2],
[0.333333333333333*(sin(theta_0^1)*cos(theta_0^2) - sin(theta_0^2)*cos(theta_0^1)*cos(phi_0^1 - phi_0^2))**2, 0.333333333333333*(sin(theta_0^1)*cos(theta_1^2) - sin(theta_1^2)*cos(theta_0^1)*cos(phi_0^1 - phi_1^2))**2],
[                                              0.333333333333333*sin(phi_0^1 - phi_0^2)**2*cos(theta_0^1)**2,                                               0.333333333333333*sin(phi_0^1 - phi_1^2)**2*cos(theta_0^1)**2],
[0.333333333333333*(sin(theta_0^1)*cos(theta_0^2)*cos(phi_0^1 - phi_0^2) - sin(theta_0^2)*cos(theta_0^1))**2, 0.333333333333333*(sin(theta_0^1)*cos(theta_1^2)*cos(phi_0^1 - phi_1^2) - sin(theta_1^2)*cos(theta_0^1))**2],
[0.333333333333333*(sin(theta_0^1)*sin(theta_0^2)*cos(phi_0^1 - phi_0^2) + cos(theta_0^1)*cos(theta_0^2))**2, 0

In [258]:
nQ1(Qt10, pi/10, pi/2, pi/2, pi/2, pi/10, -pi/4)

array([[0.032, 0.099],
       [0.302, 0.084],
       [0.   , 0.151],
       [0.302, 0.084],
       [0.032, 0.234],
       [0.   , 0.016],
       [0.   , 0.151],
       [0.   , 0.016],
       [0.333, 0.167]])

In [236]:
Qt1 = Matrix([[simplify(tr(rho(Matrix([(4/10)**0.5*1,0,0,0,(2/10)**0.5*1,0,0,0,(4/10)**0.5*1]))*tp(M1[a1](1,t1), M1[a2](2,t2)))) for (t1,t2) in list(pr(T1,T2))] for (a1,a2) in list(pr(A1,A1))])
Qt1

Matrix([
[0.2*sin(phi_0^1)**2*sin(phi_0^2)**2*cos(theta_0^1)**2*cos(theta_0^2)**2 + 0.565685424949238*sin(phi_0^1)*sin(phi_0^2)*sin(theta_0^1)*sin(theta_0^2)*cos(theta_0^1)*cos(theta_0^2) + 0.565685424949238*sin(phi_0^1)*sin(phi_0^2)*cos(phi_0^1)*cos(phi_0^2)*cos(theta_0^1)**2*cos(theta_0^2)**2 + 0.4*sin(theta_0^1)**2*sin(theta_0^2)**2 + 0.8*sin(theta_0^1)*sin(theta_0^2)*cos(phi_0^1)*cos(phi_0^2)*cos(theta_0^1)*cos(theta_0^2) + 0.4*cos(phi_0^1)**2*cos(phi_0^2)**2*cos(theta_0^1)**2*cos(theta_0^2)**2, 0.2*sin(phi_0^1)**2*sin(phi_1^2)**2*cos(theta_0^1)**2*cos(theta_1^2)**2 + 0.565685424949238*sin(phi_0^1)*sin(phi_1^2)*sin(theta_0^1)*sin(theta_1^2)*cos(theta_0^1)*cos(theta_1^2) + 0.565685424949238*sin(phi_0^1)*sin(phi_1^2)*cos(phi_0^1)*cos(phi_1^2)*cos(theta_0^1)**2*cos(theta_1^2)**2 + 0.4*sin(theta_0^1)**2*sin(theta_1^2)**2 + 0.8*sin(theta_0^1)*sin(theta_1^2)*cos(phi_0^1)*cos(phi_1^2)*cos(theta_0^1)*cos(theta_1^2) + 0.4*cos(phi_0^1)**2*cos(phi_1^2)**2*cos(theta_0^1)**2*cos(theta_1^2)**2],

In [255]:
nQ1(Qt1, pi/2, pi/2, pi/2, pi/2, pi, pi)

array([[ 0.4,  0. ],
       [ 0. ,  0.4],
       [-0. ,  0. ],
       [ 0. ,  0. ],
       [ 0.2,  0. ],
       [-0. ,  0.2],
       [-0. ,  0.4],
       [-0. ,  0. ],
       [ 0.4, -0. ]])

In [200]:
Q = lambda rho: Matrix([[simplify(tr(rho*tp(M1[a1](1,t1), M2[a2](2,t2)))) for (t1,t2) in list(pr(T1,T2))] for (a1,a2) in list(pr(A1,A2))])

In [210]:
nQ1(Q1, pi/2, pi/2, pi/2, pi/2, 0, 0)

array([[0.333, 0.   ],
       [0.   , 0.333],
       [0.   , 0.333],
       [0.333, 0.   ],
       [0.   , 0.333],
       [0.333, 0.   ]])

In [93]:
Q0 = Q(rho1)

In [136]:
nQ(Q0, pi/2, pi/6, pi/3, pi/3)

array([[0.125, 0.375],
       [0.375, 0.125],
       [0.094, 0.031],
       [0.031, 0.094],
       [0.281, 0.094],
       [0.094, 0.281]])

In [74]:
Q(rho(Matrix([1,0,1,0,0,1])))

Matrix([
[(sin(theta_0^1)*sin(theta_0^2) + sqrt(2)*sin(phi_0^1 + pi/4)*cos(theta_0^1)*cos(theta_0^2))**2, (sin(theta_0^1)*sin(theta_1^2) + sqrt(2)*sin(phi_0^1 + pi/4)*cos(theta_0^1)*cos(theta_1^2))**2],
[(sin(theta_0^1)*cos(theta_0^2) - sqrt(2)*sin(theta_0^2)*sin(phi_0^1 + pi/4)*cos(theta_0^1))**2, (sin(theta_0^1)*cos(theta_1^2) - sqrt(2)*sin(theta_1^2)*sin(phi_0^1 + pi/4)*cos(theta_0^1))**2],
[(sqrt(2)*sin(theta_0^1)*sin(phi_0^1 + pi/4)*cos(theta_0^2) - sin(theta_0^2)*cos(theta_0^1))**2, (sqrt(2)*sin(theta_0^1)*sin(phi_0^1 + pi/4)*cos(theta_1^2) - sin(theta_1^2)*cos(theta_0^1))**2],
[(sqrt(2)*sin(theta_0^1)*sin(theta_0^2)*sin(phi_0^1 + pi/4) + cos(theta_0^1)*cos(theta_0^2))**2, (sqrt(2)*sin(theta_0^1)*sin(theta_1^2)*sin(phi_0^1 + pi/4) + cos(theta_0^1)*cos(theta_1^2))**2],
[                                                    2*cos(theta_0^2)**2*cos(phi_0^1 + pi/4)**2,                                                     2*cos(theta_1^2)**2*cos(phi_0^1 + pi/4)**2],
[                    

In [206]:
Q1 = Q(rho((1/3)**0.5*Matrix([1,0,1,0,0,1])))

In [207]:
Q1

Matrix([
[0.333333333333333*(sin(theta_0^1)*sin(theta_0^2) + sqrt(2)*sin(phi_0^1 + pi/4)*cos(theta_0^1)*cos(theta_0^2))**2, 0.333333333333333*(sin(theta_0^1)*sin(theta_1^2) + sqrt(2)*sin(phi_0^1 + pi/4)*cos(theta_0^1)*cos(theta_1^2))**2],
[0.333333333333333*(sin(theta_0^1)*cos(theta_0^2) - sqrt(2)*sin(theta_0^2)*sin(phi_0^1 + pi/4)*cos(theta_0^1))**2, 0.333333333333333*(sin(theta_0^1)*cos(theta_1^2) - sqrt(2)*sin(theta_1^2)*sin(phi_0^1 + pi/4)*cos(theta_0^1))**2],
[0.333333333333333*(sqrt(2)*sin(theta_0^1)*sin(phi_0^1 + pi/4)*cos(theta_0^2) - sin(theta_0^2)*cos(theta_0^1))**2, 0.333333333333333*(sqrt(2)*sin(theta_0^1)*sin(phi_0^1 + pi/4)*cos(theta_1^2) - sin(theta_1^2)*cos(theta_0^1))**2],
[0.333333333333333*(sqrt(2)*sin(theta_0^1)*sin(theta_0^2)*sin(phi_0^1 + pi/4) + cos(theta_0^1)*cos(theta_0^2))**2, 0.333333333333333*(sqrt(2)*sin(theta_0^1)*sin(theta_1^2)*sin(phi_0^1 + pi/4) + cos(theta_0^1)*cos(theta_1^2))**2],
[                                                      0.66666666666666

In [209]:
nQ(Q1, pi/2, pi/2, 0, -pi/4)

array([[0.333, 0.   ],
       [0.   , 0.333],
       [0.   , 0.   ],
       [0.   , 0.   ],
       [0.   , 0.667],
       [0.667, 0.   ]])

In [201]:
Q2 = Q(rho((1/2)**0.5*Matrix([1,0,0,0,0,-1])))
Q2

Matrix([
[0.5*(sin(theta_0^1)*sin(theta_0^2) - cos(phi_0^1)*cos(theta_0^1)*cos(theta_0^2))**2, 0.5*(sin(theta_0^1)*sin(theta_1^2) - cos(phi_0^1)*cos(theta_0^1)*cos(theta_1^2))**2],
[0.5*(sin(theta_0^1)*cos(theta_0^2) + sin(theta_0^2)*cos(phi_0^1)*cos(theta_0^1))**2, 0.5*(sin(theta_0^1)*cos(theta_1^2) + sin(theta_1^2)*cos(phi_0^1)*cos(theta_0^1))**2],
[0.5*(sin(theta_0^1)*cos(phi_0^1)*cos(theta_0^2) + sin(theta_0^2)*cos(theta_0^1))**2, 0.5*(sin(theta_0^1)*cos(phi_0^1)*cos(theta_1^2) + sin(theta_1^2)*cos(theta_0^1))**2],
[0.5*(sin(theta_0^1)*sin(theta_0^2)*cos(phi_0^1) - cos(theta_0^1)*cos(theta_0^2))**2, 0.5*(sin(theta_0^1)*sin(theta_1^2)*cos(phi_0^1) - cos(theta_0^1)*cos(theta_1^2))**2],
[                                              0.5*sin(phi_0^1)**2*cos(theta_0^2)**2,                                               0.5*sin(phi_0^1)**2*cos(theta_1^2)**2],
[                                              0.5*sin(phi_0^1)**2*sin(theta_0^2)**2,                                              

In [204]:
nQ(Q2, pi/2, 0, pi/2, pi/4)

array([[0.  , 0.5 ],
       [0.5 , 0.  ],
       [0.25, 0.  ],
       [0.  , 0.25],
       [0.25, 0.  ],
       [0.  , 0.25]])

In [137]:
Q2 = Q(rho((1/3)**0.5*Matrix([1,0,0,1,0,1])))
Q2

Matrix([
[0.333333333333333*(sin(theta_0^1)*sin(theta_0^2) + cos(theta_0^1)*cos(phi_0^1 - theta_0^2))**2, 0.333333333333333*(sin(theta_0^1)*sin(theta_1^2) + cos(theta_0^1)*cos(phi_0^1 - theta_1^2))**2],
[0.333333333333333*(sin(theta_0^1)*cos(theta_0^2) + sin(phi_0^1 - theta_0^2)*cos(theta_0^1))**2, 0.333333333333333*(sin(theta_0^1)*cos(theta_1^2) + sin(phi_0^1 - theta_1^2)*cos(theta_0^1))**2],
[0.333333333333333*(sin(theta_0^1)*cos(phi_0^1 - theta_0^2) - sin(theta_0^2)*cos(theta_0^1))**2, 0.333333333333333*(sin(theta_0^1)*cos(phi_0^1 - theta_1^2) - sin(theta_1^2)*cos(theta_0^1))**2],
[0.333333333333333*(sin(theta_0^1)*sin(phi_0^1 - theta_0^2) - cos(theta_0^1)*cos(theta_0^2))**2, 0.333333333333333*(sin(theta_0^1)*sin(phi_0^1 - theta_1^2) - cos(theta_0^1)*cos(theta_1^2))**2],
[                                                 0.333333333333333*sin(phi_0^1 - theta_0^2)**2,                                                  0.333333333333333*sin(phi_0^1 - theta_1^2)**2],
[                    

In [161]:
nQ(Q2, pi/2, 0, pi/2, pi/2)

array([[0.   , 0.333],
       [0.333, 0.   ],
       [0.   , 0.333],
       [0.333, 0.   ],
       [0.333, 0.   ],
       [0.   , 0.333]])

In [162]:
Q3 = Q(rho(Matrix([(6/9)**0.5,0,0,(2/9)**0.5,0,(1/9)**0.5])))
Q3

Matrix([
[0.0555555555555556*cos(2*phi_0^1) + 0.0833333333333333*cos(2*theta_0^1) + 0.0277777777777778*cos(2*theta_0^2) + 0.0392837100659193*cos(phi_0^1 - 2*theta_0^1) - 0.0392837100659193*cos(phi_0^1 + 2*theta_0^1) + 0.0277777777777778*cos(2*phi_0^1 - 2*theta_0^1) + 0.0277777777777778*cos(2*phi_0^1 + 2*theta_0^1) + 0.103668077988024*cos(2*phi_0^1 - 2*theta_0^2) + 0.00744303312308674*cos(2*phi_0^1 + 2*theta_0^2) + 0.0416666666666667*cos(2*theta_0^1 - 2*theta_0^2) + 0.0416666666666667*cos(2*theta_0^1 + 2*theta_0^2) + 0.0518340389940122*cos(-2*phi_0^1 + 2*theta_0^1 + 2*theta_0^2) - 0.0536625459049482*cos(-phi_0^1 + 2*theta_0^1 + 2*theta_0^2) + 0.0143788358390289*cos(phi_0^1 - 2*theta_0^1 + 2*theta_0^2) + 0.0536625459049482*cos(phi_0^1 + 2*theta_0^1 - 2*theta_0^2) - 0.0143788358390289*cos(phi_0^1 + 2*theta_0^1 + 2*theta_0^2) + 0.00372151656154337*cos(2*phi_0^1 - 2*theta_0^1 + 2*theta_0^2) + 0.0518340389940122*cos(2*phi_0^1 + 2*theta_0^1 - 2*theta_0^2) + 0.00372151656154337*cos(2*phi_0^1 +

In [163]:
nQ(Q3, pi/2, 0, pi/2, pi/2)

array([[ 0.   ,  0.111],
       [ 0.111,  0.   ],
       [ 0.   ,  0.222],
       [ 0.222,  0.   ],
       [ 0.667, -0.   ],
       [-0.   ,  0.667]])

In [33]:
Q[:,0]

Matrix([
[0.5*(sin(theta_0^1)*sin(theta_0^2) + cos(phi_0^1)*cos(theta_0^1)*cos(theta_0^2))**2],
[0.5*(sin(theta_0^1)*cos(theta_0^2) - sin(theta_0^2)*cos(phi_0^1)*cos(theta_0^1))**2],
[0.5*(sin(theta_0^1)*cos(phi_0^1)*cos(theta_0^2) - sin(theta_0^2)*cos(theta_0^1))**2],
[0.5*(sin(theta_0^1)*sin(theta_0^2)*cos(phi_0^1) + cos(theta_0^1)*cos(theta_0^2))**2],
[                                              0.5*sin(phi_0^1)**2*cos(theta_0^2)**2],
[                                              0.5*sin(phi_0^1)**2*sin(theta_0^2)**2]])

In [83]:
s = 0 
for i in Q1[:,0]:
    s += i

simplify(s)    

1.00000000000000

In [43]:
l = sin(th(1,0))
f = lambdify([th(1,0)], l)
f(0)

0.0

In [62]:
f = lambdify([th(1,0), th(2,0), th(2,1), ph(1,0)], Q)

In [71]:
around(f(pi/2, 0, pi/2, 0), decimals=1)

array([[0. , 0.5],
       [0.5, 0. ],
       [0.5, 0. ],
       [0. , 0.5],
       [0. , 0. ],
       [0. , 0. ]])

In [59]:
pi

3.141592653589793

In [39]:
th(1,0)

theta_0^1

In [4]:
ph(1,0)

phi_0^1

In [12]:
from sympy.abc import x, y, z, t, p

In [22]:
solve((cos(p)*cos(t)*x + sin(p)*cos(t)*y + sin(t)*z, cos(p)*sin(t)*x + sin(p)*sin(t)*y -cos(t)*z, x**2 + y**2 + z**2 - 1), x, y, z)

[(-sin(p), cos(p), 0), (sin(p), -cos(p), 0)]

(-z*cos(p)*tan(t) - sqrt(-z**2 + cos(t)**2)*sin(p)/cos(t), -z*sin(p)*tan(t) + sqrt(-z**2 + cos(t)**2)*cos(p)/cos(t), z)